server:
  port: 8080

spring:
  datasource:
    username: root
    password: testpass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true

# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: https://dimonvideo.ru
#      name: dimonvideo
#    - url: http://mir-kuhni.ru
#      name: Mir kuhni

jsoup-setting:
  userAgent: Sergei's searching bot
  referrer: http://www.google.com
  timeout: 5000
  ignoreHttpErrors: true
  followRedirects: true