server:
  port: 8080

spring:
  datasource:
    username: root
    password: testpass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
#    show-sql: true

# example values

indexing-settings:
  sites:
    - url: https://radiomv.ru/
      name: Radio MV
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://et-cetera.ru/mobile
      name: Et Cetera
    - url: https://www.playback.ru
      name: PlayBack.Ru
#    - url: https://dimonvideo.ru
#      name: dimonvideo

jsoup-setting:
  userAgent: Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
  referrer: http://www.google.com
  timeout: 5000
  ignoreHttpErrors: true
  followRedirects: true